import { v4 as uuidv4 } from 'uuid';
interface Person {
    id: string;
    name: string;
    position: string;
    image: string;
    linkedin: string;
    instagram: string;
    facebook: string;
}

export const founderAdvisors : Person[] = [
    {
        id: uuidv4(),
        name: 'Prakhar Jain',
        position: 'Advisor',
        image: "/team/prakhar_jain.jpeg",
        linkedin: "https://www.linkedin.com/in/prakhar-jain-4bb879227/",
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Nishim Goyal',
        position: 'Advisor',
        image: '/team/nishim_goyal.jpeg',
        linkedin: 'https://www.linkedin.com/in/nishim-goyal/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Sameer Sen',
        position: 'Advisor',
        image:'/team/sameer_sen.jpeg',
        linkedin: 'https://www.linkedin.com/in/sameer-sen-82a82a244/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Suvojit Das',
        position: 'Advisor',
        image: '/team/suvojit_das.jpeg',
        linkedin: 'https://www.linkedin.com/in/suvojit-das-89aa5124b/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Ayush Kumar',
        position: 'Advisor',
        image: '/team/ayush_kumar.jpeg',
        linkedin: 'https://www.linkedin.com/in/ayush-kumar-b3b701232/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Avhinav Prakash',
        position: 'Advisor',
        image: '/team/abhinav_prakash.jpeg',
        linkedin: 'https://www.linkedin.com/in/psychopunksage/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'SSVKSS Jyothiraditya',
        position: 'Advisor',
        image: '/team/SSVKSS_jyothiraditya.jpeg',
        linkedin: 'https://www.linkedin.com/in/ssvkss-jyothiraditya-21200322b/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Diptendu Sarkar',
        position: 'Advisor',
        image: '/team/diptendu_sarkar.jpeg',
        linkedin: 'https://www.linkedin.com/in/diptendu-sarkar-397142205/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Ojas Deshmukh',
        position: 'Advisor',
        image: '/team/ojas_deshmukh.jpeg',
        linkedin: 'https://www.linkedin.com/in/ojas-deshmukh-4a2a041a2/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Atharva Amritkar',
        position: 'Advisor',
        image: '/team/atharva_amritkar.jpeg', 
        linkedin: 'https://www.linkedin.com/in/wiredhikari/',
        instagram: '/',
        facebook: '/',
    },
    
    {
        id: uuidv4(),
        name: 'Druhin Abrol',
        position: 'Advisor',
        image: '/team/druhin_abrol.jpeg', 
        linkedin: 'https://www.linkedin.com/in/druhinabrol/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Mohith Suresh',
        position: 'Advisor',
        image: '/team/mohith_suresh.jpeg',
        linkedin: 'https://www.linkedin.com/in/mohith-suresh/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Samarth Singh',
        position: 'Advisor',
        image: '/team/samarth_singh.jpeg',
        linkedin: 'https://www.linkedin.com/in/samarth-singh-2003/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Soham Sen',
        position: 'Advisor',
        image: '/team/soham_sen.jpeg',
        linkedin: 'https://www.linkedin.com/in/sohamsendev/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Tushar Kanwaria',
        position: 'Advisor',
        image: '/team/tushar_kanwaria.jpeg',
        linkedin: 'https://www.linkedin.com/in/tusharkanwaria/',
        instagram: '/',
        facebook: '/',
    },
]

export const governorHeads : Person[] = [
    {
        id: uuidv4(),
        name: 'Swarnendu Bhandari',
        position: 'Governor',
        image: '/team/swarnendu_bhandari.jpeg',
        linkedin: 'https://www.linkedin.com/in/swarnendu-bhandari-847590290/',
        instagram: 'https://www.instagram.com/swarnendu_iit_kgp/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Ishan Sharma',
        position: 'Operations Head',
        image: '/team/ishan_sharma.jpeg',
        linkedin: 'https://www.linkedin.com/in/ishan-sharma-307648256/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Saroja Bamra',
        position: 'Tech Head',
        image: '/team/saroja_bamra.jpeg',
        linkedin: 'https://www.linkedin.com/in/saroja-bamra-27648624a/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Smriti Kumari',
        position: 'DeFi Head',
        image: '/team/smriti_kumari.jpeg',
        linkedin: 'https://www.linkedin.com/in/smriti-kumari-884026257/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Abhranil Mondal',
        position: 'Research Head',
        image: '/team/abhranil_mondal.jpeg',
        linkedin: 'https://www.linkedin.com/in/abhranil-mondal-8b8098230/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Sagnik Roy',
        position: 'Research Head',
        image: '/team/sagnik_roy.jpeg',
        linkedin: 'https://www.linkedin.com/in/sagnik-roy-187591251/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Twinkle Chatterjee',
        position: 'Operations Head',
        image: '/team/twinkle_chatterjee.jpeg',
        linkedin: 'https://www.linkedin.com/in/twinkle-chatterjee-0066651b2/',
        instagram: '/',
        facebook: '/',
    },
    {
        id: uuidv4(),
        name: 'Simran Simran',
        position: 'Operations Head',
        image: '/team/simran_simran.jpeg',
        linkedin: 'https://www.linkedin.com/in/simran-simran-6b5873256/',
        instagram: '/',
        facebook: '/',
    },

]
export type { Person };